#!/usr/bin/env python
# Peter Hausel 
# 2011-05-01
# -- rename to sr
# -- color output
# -- optional file regexp
# -- include only source files and certain text files types by default
# regexplace: regular expression search and replace
# Stefano Spinucci
# 2006-02-07 (rev 4)

# thanks to roadrunner.py
# http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/52553
# for some ideas and some code

# tested with python 2.6.1



import sys, os, re, string



# pupulate and return 'fileslist[]' with all files inside 'dir' matching 'regx'
def make_files_list(dir, regx):

    # if dir is not a directory, exit with error
    if not os.path.isdir(dir):
        sys.exit(dir + ' is not a valid dir to walk !!!')

    # compile the search regexp
    cregex=re.compile(regx)

    # initialize the file list
    fileslist = []

    # loop on all files and select files matching 'regx'
    for root, dirs, files in os.walk(dir):
        for name in files:
            if cregex.search(name) and name.endswith(".class") != True \
                    and name.endswith(".war") != True \
                    and name.endswith(".pyc") != True \
                    and name.endswith(".jar") != True:
                path = os.path.join(root, name)
                fileslist.append(path)

    # return the file list
    return fileslist[:]



# in all files in 'fileslist' search the regexp 'searchregx' and replace
# with 'replacestring'; real substitution in files only if 'simulation' = 0;
# real substitution may also be step by step (if 'stepbystep' = 1)
def replace_in_files(fileslist, searchregx, replacestring, simulation, stepbystep):

    # compile regexp
    cregex=re.compile(searchregx)

    # print message to the user
    if simulation == 1:
        print '\nReplaced (simulation):\n'
    else:
        print '\nReplaced:\n'

    # loop on all files
    for xfile in fileslist:

        # initialize the replace flag
        replaceflag=0

        # open file for read  
        readlines=open(xfile,'r').readlines()
        # intialize the list counter
        listindex = -1
        # search and replace in current file printing to the user changed lines
        for currentline in readlines:

            # increment the list counter
            listindex = listindex + 1

            # if the regexp is found
            if cregex.search(currentline):

                # make the substitution
                f = re.sub(searchregx,replacestring,currentline)
                highlight = re.sub(searchregx,'\033[93m' +searchregx+'\033[m',currentline)
                replace_highlight = re.sub(searchregx,'\033[91m' +replacestring+'\033[m',currentline)
                # print the current filename, the old string and the new string
                print '\033[92m' +'\n' + xfile+'\033[m'
                print '- ' + str(listindex+1) +':'+ highlight ,
                if currentline[-1:]!='\n': print '\n' ,
                print '+ ' + str(listindex+1) +':'+replace_highlight ,
                if f[-1:]!='\n': print '\n' ,

                # if substitution is real
                if simulation == 0:

                    # if substitution is step by step
                    if stepbystep == 1:

                        # ask user if the current line must be replaced
                        question = raw_input('write(Y), skip (n), quit (q) ? ')
                        question = string.lower(question)

                        # if quit
                        if question=='q':
                            sys.exit('\ninterrupted by the user !!!')

                        # if skip
                        elif question=='n':
                            pass

                        # if write
                        else:

                            # update the whole file variable ('readlines')
                            readlines[listindex] = f
                            replaceflag=1

                    # if substitution is not step by step
                    else:

                            # update the whole file variable ('readlines')
                            readlines[listindex] = f
                            replaceflag=1
        # if some text was replaced
        # overwrite the original file
        if replaceflag==1:

            # open the file for writting  
            write_file=open(xfile,'w') 

            # overwrite the file  
            for line in readlines:
                write_file.write(line)

            # close the file
            write_file.close()



# main function
def main():

    # if parameters are wrong, exit with error
    if len(sys.argv) < 4:

        print '\nUsage:'
        print 'sr dirname [files-regexp] search-regexp replace-string'

        sys.exit(1)
    if len(sys.argv) == 4:
        dirname = sys.argv[1]
        search_regexp = sys.argv[2]
        replace_string = sys.argv[3]
        file_regexp = ".*.txt|README|.*.textile|.*.html|.*.css|.*.js|.*.scala|.*.xml|.*.rb|.*.py|.*.conf|.*.java|.*.properties|.*.yaml|.*.c|.*.cpp|.*.o|.*.groovy"

    if len(sys.argv) == 5:
        dirname = sys.argv[1]
        file_regexp = sys.argv[2]
        search_regexp = sys.argv[3]
        replace_string = sys.argv[4]

    # ask user for simulated execution or real substitution
    print '\nyou are replacing \033[93m%s\033[m with \033[91m%s\033[m in %s' %(search_regexp, replace_string, dirname)
    question1 = raw_input('continue with real substitution (y/N) ? ')
    question1 = string.lower(question1)

    # if user selected real substitution, ask user if execution must be step by step
    if question1=='y':
        question2 = raw_input('\nsubstitute step by step (Y/n) ? ')
        question2 = string.lower(question2)

    # make the file list
    fileslist = make_files_list(dirname, file_regexp)

    # if real substitution
    if question1=='y':

        # if step by step
        if question2!='n':
            replace_in_files(fileslist, search_regexp, replace_string, 0, 1)

        # if not step by step
        else:
            replace_in_files(fileslist, search_regexp, replace_string, 0, 0)        

    # if simulated execution
    else:
        replace_in_files(fileslist, search_regexp, replace_string, 1, 0)
                
            
if __name__ == '__main__':
    main()            
            
            
